[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/var/www/app/var/supervisord.pid
childlogdir=/var/www/app/var/log/supervisor

[program:messenger-consume]
command=php /var/www/app/bin/console messenger:consume async --time-limit=3600
directory=/var/www/app
autostart=true
autorestart=true
startsecs=3
startretries=3
stdout_logfile=/var/www/app/var/log/supervisor/messenger-consume.stdout.log
stderr_logfile=/var/www/app/var/log/supervisor/messenger-consume.stderr.log